// REGULATOR & COMPLIANCE ROUTES - Part XIX Blueprint v3.1
// FRA Dashboard, EGX Alignment, GAFI Bidirectional Sync, Tax Authority
import { Hono } from 'hono'
import { verifyToken, logAudit } from '../utils/auth'

export const regulatorRoutes = new Hono()

// GET /fra-dashboard - FRA Read-Only Dashboard (Part XIX.1)
regulatorRoutes.get('/fra-dashboard', async (c) => {
  const token = c.req.header('Authorization')?.replace('Bearer ', '')
  const auth = verifyToken(token || '')
  if (!auth) return c.json({ error: 'Unauthorized' }, 401)
  
  // Verify regulator role
  const { env } = c
  const user = await env.DB.prepare('SELECT role FROM users WHERE id = ?').bind(auth.uid).first()
  if (!user || !['admin', 'regulator'].includes((user as any).role)) {
    return c.json({ error: 'Regulator access required' }, 403)
  }
  
  // Active projects by tier
  const projectsByTier = await env.DB.prepare(`
    SELECT tier, status, COUNT(*) as count, SUM(funding_raised) as total_raised, SUM(funding_goal) as total_goal,
    AVG(health_score) as avg_health, AVG(ai_feasibility_score) as avg_feasibility
    FROM projects GROUP BY tier, status
  `).all()
  
  // Aggregate escrow balances per law firm
  const escrowByLawFirm = await env.DB.prepare(`
    SELECT p.law_firm_id, u.full_name as law_firm_name,
    SUM(CASE WHEN et.status = 'completed' THEN et.amount ELSE 0 END) as total_completed,
    SUM(CASE WHEN et.status = 'pending' THEN et.amount ELSE 0 END) as total_pending,
    SUM(CASE WHEN et.status = 'frozen' THEN et.amount ELSE 0 END) as total_frozen
    FROM escrow_transactions et
    JOIN projects p ON et.project_id = p.id
    LEFT JOIN users u ON p.law_firm_id = u.id
    GROUP BY p.law_firm_id
  `).all()
  
  // Governance events count
  const governanceEvents = await env.DB.prepare(`
    SELECT event_type, COUNT(*) as count FROM governance_events
    GROUP BY event_type ORDER BY count DESC
  `).all()
  
  // Secondary market volume
  const marketVolume = await env.DB.prepare(`
    SELECT COUNT(*) as total_orders,
    SUM(CASE WHEN status = 'completed' THEN ask_price * shares_count ELSE 0 END) as completed_volume,
    SUM(shares_count) as total_shares
    FROM market_orders
  `).first()
  
  // Jobs created
  const jobs = await env.DB.prepare("SELECT COUNT(*) as total FROM employee_registry WHERE status = 'active'").first()
  
  // Tax estimates
  const taxRecords = await env.DB.prepare('SELECT tax_type, SUM(tax_amount) as total FROM tax_records GROUP BY tax_type').all()
  
  // Disputes summary
  const disputes = await env.DB.prepare('SELECT status, COUNT(*) as count FROM disputes GROUP BY status').all()
  
  // Risk alerts active
  const risks = await env.DB.prepare("SELECT alert_level, COUNT(*) as count FROM risk_alerts WHERE status = 'active' GROUP BY alert_level").all()
  
  return c.json({
    dashboard_type: 'FRA Read-Only Dashboard',
    access_level: 'regulator',
    generated_at: new Date().toISOString(),
    projects_by_tier: projectsByTier.results,
    escrow_balances: escrowByLawFirm.results,
    governance_events: governanceEvents.results,
    secondary_market: {
      total_orders: (marketVolume as any)?.total_orders || 0,
      completed_volume_egp: (marketVolume as any)?.completed_volume || 0,
      total_shares_traded: (marketVolume as any)?.total_shares || 0,
      pricing_model: 'Fundamental-only (Rule 9)',
      anonymized: true
    },
    employment: {
      jobs_created: (jobs as any)?.total || 0,
      source: 'Employee registry (anonymized aggregate)'
    },
    tax_contributions: taxRecords.results,
    disputes_summary: disputes.results,
    active_risks: risks.results,
    constitutional_compliance: {
      zero_custody: 'VERIFIED - Platform never holds funds',
      escrow_separation: 'VERIFIED - Law firm escrow only',
      ai_enforcement: 'ACTIVE - No human override of core rules',
      immutable_audit: 'ACTIVE - Append-only ledger operational',
      fundamental_pricing: 'ACTIVE - Rule 9 enforced'
    },
    blueprint_reference: 'Part XIX.1 - FRA Read-Only Dashboard'
  })
})

// GET /egx-alignment - EGX Alignment Report (Part XIX.1)
regulatorRoutes.get('/egx-alignment', async (c) => {
  const token = c.req.header('Authorization')?.replace('Bearer ', '')
  const auth = verifyToken(token || '')
  if (!auth) return c.json({ error: 'Unauthorized' }, 401)
  
  const { env } = c
  const ipoReadyProjects = await env.DB.prepare(`
    SELECT id, title, tier, sector, pre_money_valuation, health_score, ai_feasibility_score
    FROM projects WHERE pre_money_valuation >= 50000000 AND health_score >= 70
    ORDER BY pre_money_valuation DESC
  `).all()
  
  return c.json({
    egx_alignment: {
      reporting_standard: 'IFRS for SMEs - automated quarterly/annual generation',
      governance_standards: 'Exceeds EGX minimum via constitutional governance',
      sme_exchange_compatible: true,
      financial_reporting_templates: 'Auto-generated by SHERKETI financial system',
      ipo_ready_projects: ipoReadyProjects.results?.map((p: any) => ({
        id: p.id, title: p.title, tier: p.tier, sector: p.sector,
        valuation: p.pre_money_valuation, health_score: p.health_score
      }))
    },
    continuous_disclosure: {
      quarterly_reports: 'Auto-generated and notarized',
      governance_events: 'Real-time immutable ledger',
      material_changes: 'Instant notification system'
    },
    blueprint_reference: 'Part XIX.1 - EGX Alignment'
  })
})

// POST /gafi-sync - GAFI Bidirectional Sync (Part XIX.1 / Add-on 15)
regulatorRoutes.post('/gafi-sync', async (c) => {
  const token = c.req.header('Authorization')?.replace('Bearer ', '')
  const auth = verifyToken(token || '')
  if (!auth) return c.json({ error: 'Unauthorized' }, 401)
  
  const { project_id, sync_type } = await c.req.json()
  if (!project_id || !sync_type) return c.json({ error: 'project_id and sync_type required' }, 400)
  
  const { env } = c
  const project = await env.DB.prepare('SELECT * FROM projects WHERE id = ?').bind(project_id).first()
  if (!project) return c.json({ error: 'Project not found' }, 404)
  
  const p = project as any
  const gafiRefNumber = `GAFI-${Date.now()}-${project_id}`
  
  const syncActions: Record<string, any> = {
    company_registration: {
      action: 'Submit registration documents to GAFI',
      documents: ['Trade name reservation', 'Commercial registry application', 'Fee payment'],
      estimated_time: '3-5 business days (reduced from weeks)',
      gafi_endpoint: '/api/v1/company/register'
    },
    compliance_check: {
      action: 'Pull compliance status from GAFI webhooks',
      checks: ['License renewal status', 'Regulatory fines', 'Ownership changes'],
      gafi_endpoint: '/api/v1/company/compliance'
    },
    incentive_application: {
      action: 'Apply for investment incentives via GAFI',
      eligible_incentives: p.company_region === 'upper_egypt'
        ? ['Tax deduction up to 50% for 7 years', 'Land allocation', 'Import duty exemption']
        : ['Tax deduction up to 30%', 'Customs reduction'],
      gafi_endpoint: '/api/v1/incentives/apply'
    },
    foreign_investment: {
      action: 'Register foreign investment with GAFI',
      compliance: 'Foreign ownership limit enforcement (49% for restricted sectors)',
      gafi_endpoint: '/api/v1/foreign-investment/register'
    },
    golden_license: {
      action: 'Submit Golden License application for strategic projects',
      eligibility: p.tier === 'C' || p.tier === 'D' ? 'potentially_eligible' : 'not_eligible',
      sectors: ['Large-scale manufacturing', 'Renewable energy', 'Strategic infrastructure'],
      gafi_endpoint: '/api/v1/golden-license/apply'
    },
    investment_map_sync: {
      action: 'Sync project to GAFI Investment Map',
      bidirectional: true,
      data: { sector: p.sector, region: p.company_region, valuation: p.pre_money_valuation },
      gafi_endpoint: '/api/v1/investment-map/sync'
    },
    ubo_validation: {
      action: 'Validate Ultimate Beneficial Owner information',
      gafi_endpoint: '/api/v1/ubo/validate'
    }
  }
  
  const syncAction = syncActions[sync_type]
  if (!syncAction) return c.json({ error: 'Invalid sync_type. Valid: ' + Object.keys(syncActions).join(', ') }, 400)
  
  // Record GAFI registration
  await env.DB.prepare(`
    INSERT INTO gafi_registrations (project_id, registration_type, status, gafi_reference_number, submission_data, submitted_at)
    VALUES (?, ?, ?, ?, ?, ?)
  `).bind(project_id, sync_type, 'submitted', gafiRefNumber, JSON.stringify(syncAction), new Date().toISOString()).run()
  
  await logAudit(env.DB, 'gafi_sync', 'project', project_id, auth.uid, JSON.stringify({ sync_type, gafiRefNumber }))
  
  return c.json({
    project_id,
    sync_type,
    gafi_reference: gafiRefNumber,
    action: syncAction,
    status: 'submitted',
    api_protocol: {
      authentication: 'OAuth 2.0 with client credentials (Appendix G)',
      data_format: 'JSON/REST',
      rate_limit: '100 requests/minute/project',
      error_handling: 'Exponential backoff; manual fallback (email) if unavailable >1 hour'
    },
    blueprint_reference: 'Part XIX.1 / Add-on 15 / Appendix G'
  })
})

// GET /gafi-registrations/:projectId - Get GAFI registration history
regulatorRoutes.get('/gafi-registrations/:projectId', async (c) => {
  const token = c.req.header('Authorization')?.replace('Bearer ', '')
  const auth = verifyToken(token || '')
  if (!auth) return c.json({ error: 'Unauthorized' }, 401)
  
  const projectId = c.req.param('projectId')
  const regs = await c.env.DB.prepare('SELECT * FROM gafi_registrations WHERE project_id = ? ORDER BY created_at DESC').bind(projectId).all()
  return c.json({ registrations: regs.results })
})

// POST /tax-filing - Automated Tax Filing (Part XIX.1)
regulatorRoutes.post('/tax-filing', async (c) => {
  const token = c.req.header('Authorization')?.replace('Bearer ', '')
  const auth = verifyToken(token || '')
  if (!auth) return c.json({ error: 'Unauthorized' }, 401)
  
  const { project_id, tax_type, period, amount } = await c.req.json()
  if (!project_id || !tax_type || !amount) return c.json({ error: 'project_id, tax_type, amount required' }, 400)
  
  const { env } = c
  
  // Tax rates per Part XIX.1
  const taxRates: Record<string, any> = {
    capital_gains: { rate: 0.10, name: 'Capital Gains Tax', form: 'Form 41', authority: 'Egyptian Tax Authority', notes: 'Secondary market trades' },
    vat: { rate: 0.14, name: 'VAT', form: 'Monthly VAT return', authority: 'Egyptian Tax Authority', notes: 'Reduced rates for certain sectors' },
    stamp_duty: { rate: 0.004, name: 'Stamp Duty', form: 'Per transaction', authority: 'Egyptian Tax Authority' },
    dividend_withholding: { rate: 0.10, name: 'Dividend Withholding Tax', form: 'Form 41', authority: 'Egyptian Tax Authority' }
  }
  
  const tax = taxRates[tax_type]
  if (!tax) return c.json({ error: 'Invalid tax_type' }, 400)
  
  const taxAmount = amount * tax.rate
  
  // Generate Form 41 for capital gains
  const form41 = (tax_type === 'capital_gains' || tax_type === 'dividend_withholding') ? {
    form_number: 'Form 41',
    generated: true,
    data: {
      taxpayer_project_id: project_id,
      period: period || new Date().toISOString().substring(0, 7),
      gross_amount: amount,
      tax_rate: tax.rate * 100 + '%',
      tax_amount: taxAmount,
      net_amount: amount - taxAmount,
      authority: tax.authority
    },
    submission_status: 'auto_generated_ready_for_submission'
  } : null
  
  // Record tax
  await env.DB.prepare(`
    INSERT INTO tax_records (project_id, user_id, tax_type, gross_amount, tax_rate, tax_amount, period, form_type, status)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
  `).bind(project_id, auth.uid, tax_type, amount, tax.rate, taxAmount, period || new Date().toISOString().substring(0, 7), tax_type === 'capital_gains' || tax_type === 'dividend_withholding' ? 'form_41' : 'standard', 'calculated').run()
  
  await logAudit(env.DB, 'tax_filing', 'project', project_id, auth.uid, JSON.stringify({ tax_type, amount, taxAmount }))
  
  return c.json({
    project_id,
    tax_calculation: {
      type: tax.name,
      gross_amount: amount,
      tax_rate: (tax.rate * 100).toFixed(1) + '%',
      tax_amount: Math.round(taxAmount * 100) / 100,
      net_amount: Math.round((amount - taxAmount) * 100) / 100,
      authority: tax.authority
    },
    form_41: form41,
    vat_notes: tax_type === 'vat' ? 'Standard rate 14%. Reduced rates may apply for agriculture, healthcare sectors.' : undefined,
    status: 'calculated',
    next_step: 'Submit to Egyptian Tax Authority via automated filing system',
    blueprint_reference: 'Part XIX.1 - Tax Authority Automation'
  })
})

// POST /regulator-report - Generate regulator compliance report
regulatorRoutes.post('/regulator-report', async (c) => {
  const token = c.req.header('Authorization')?.replace('Bearer ', '')
  const auth = verifyToken(token || '')
  if (!auth) return c.json({ error: 'Unauthorized' }, 401)
  
  const { report_type, period } = await c.req.json()
  if (!report_type) return c.json({ error: 'report_type required' }, 400)
  
  const { env } = c
  
  let reportData: any = {}
  
  switch (report_type) {
    case 'quarterly_summary': {
      const projects = await env.DB.prepare("SELECT COUNT(*) as total, SUM(funding_raised) as raised FROM projects WHERE status != 'draft'").first()
      const users = await env.DB.prepare('SELECT COUNT(*) as total FROM users').first()
      reportData = { total_projects: (projects as any)?.total, total_raised: (projects as any)?.raised, total_users: (users as any)?.total }
      break
    }
    case 'compliance_incidents': {
      const incidents = await env.DB.prepare("SELECT * FROM risk_alerts WHERE alert_level = 'red' ORDER BY created_at DESC LIMIT 50").all()
      reportData = { incidents: incidents.results, count: incidents.results?.length }
      break
    }
    default:
      reportData = { note: 'Report type supported: quarterly_summary, escrow_balances, governance_events, market_volume, jobs_created, tax_contributions, compliance_incidents' }
  }
  
  await env.DB.prepare(`
    INSERT INTO regulator_reports (report_type, period, data, status)
    VALUES (?, ?, ?, ?)
  `).bind(report_type, period || new Date().toISOString().substring(0, 7), JSON.stringify(reportData), 'generated').run()
  
  return c.json({
    report_type,
    period: period || new Date().toISOString().substring(0, 7),
    data: reportData,
    status: 'generated',
    blueprint_reference: 'Part XIX.1 - Regulatory Reporting'
  })
})

// GET /public-transparency - Public transparency (Part XIX.3)
regulatorRoutes.get('/public-transparency', async (c) => {
  const { env } = c
  const stats = await env.DB.prepare(`
    SELECT COUNT(*) as total_projects, SUM(funding_raised) as total_raised,
    SUM(CASE WHEN status IN ('active','operational') THEN 1 ELSE 0 END) as active_projects
    FROM projects WHERE status != 'draft'
  `).first()
  
  const jobs = await env.DB.prepare("SELECT COUNT(*) as total FROM employee_registry WHERE status = 'active'").first()
  const users = await env.DB.prepare("SELECT COUNT(*) as total FROM users WHERE verification_status = 'verified'").first()
  
  return c.json({
    publicly_visible: true,
    no_login_required: true,
    constitutional_principles: {
      rule_1: 'Zero Custody - SHERKETI never holds funds',
      rule_2: 'Escrow-Only Capital Flow via licensed law firms',
      rule_3: 'AI-Locked Governance - immutable algorithms',
      rule_4: 'Human-Proof Enforcement',
      rule_5: 'Immutable Auditability - blockchain-based ledger',
      rule_6: 'One Identity Rule - one ID per account forever',
      rule_7: 'Transparency Mandate',
      rule_8: 'Platform Fee: 2.5% cash + 2.5% equity (all tiers)',
      rule_9: 'Fundamental-Only Share Pricing (non-amendable)',
      rule_10: 'Founder Partner Limitation Right'
    },
    zero_custody_proof: {
      mechanism: 'All funds flow directly to licensed Egyptian law-firm escrow accounts',
      audit: 'Monthly third-party audit confirms zero platform custody',
      verification: 'Real-time escrow balance reporting via law firm API'
    },
    platform_statistics: {
      total_projects: (stats as any)?.total_projects || 0,
      active_projects: (stats as any)?.active_projects || 0,
      total_capital_deployed_egp: (stats as any)?.total_raised || 0,
      verified_users: (users as any)?.total || 0,
      jobs_created: (jobs as any)?.total || 0,
      fee_structure: '2.5% cash commission + 2.5% equity stake (uniform all tiers)'
    },
    not_publicly_visible: [
      'Proprietary algorithm weights and thresholds',
      'Individual user data',
      'Company financial details (only visible to company shareholders)',
      'Internal AI model parameters'
    ],
    blueprint_reference: 'Part XIX.3 - Public Transparency Features'
  })
})
